[package]
before_cmds = [
    "composer install",
    "npm install",
    "npm run build",
    "vendor/bin/mozart compose",
    "composer remove eid-login/php-saml",
    "composer update --no-dev -n",
]